### ISSUE TITLE
Custom Html

### ISSUE THREAD

**Issue by Cactice** [rukai/cargo-run-wasm#3]
Appreciate your work on this project! 

However, I'm not a big fan of the h1 tag showing the name of the project.
I don't think people need to see their project name as h1 and there doesn't seem to be an option to remove it.

```
  <h1>{{name}}</h1>
```

I think there should be a way to provide your custom index.template.html
https://github.com/rukai/cargo-run-wasm/blob/main/src/index.template.html

**Comment by Cactice** [comment]
```
        web_sys::window()
            .and_then(|win| win.document())
            .and_then(|doc| doc.body())
            .and_then(|body| {
                body.remove_child(&body.last_element_child().unwrap());
            })
```
A quick workaround I'll use for now to remove h1.

**Comment by haraldreingruber-dedalus** [comment]
> A quick workaround I'll use for now to remove h1.

Thanks for the workaround. That was exactly what I was looking for.
But I see how the h1 element might be useful when you want to provide several examples.

**Comment by Cactice** [comment]
Yes the h1 can be there if the user desires it.
I've updated my first comment and added below lines

*I think there should be a way to provide your custom index.template.html*
*https://github.com/rukai/cargo-run-wasm/blob/main/src/index.template.html*

**Comment by rukai** [comment]
Hi, I havent had a chance to look yet, lifes been really busy, I will eventually though, sorry for the delay.

**Comment by Cactice** [comment]
No problem👍

**Comment by parasyte** [comment]
I wanted custom CSS in the HTML index, so I created #5 to add support for this feature. It's very simple, no-frills; just panics if the path cannot be read. Exactly what I needed.

**Comment by rukai** [comment]
I've finally gotten around to this, thanks @parasyte for the nudge.
Please try out the latest git and let me know if you hit any limitations or issues, I'll release a 0.2 once I've gotten some feedback from the wgpu and winit teams.

**Comment by parasyte** [comment]
I gave it a whirl and it works for me.

Playing devil's advocate, I can't be sure that it works with all use cases. For instance, I was given this minimal test case the other day and it has a custom JavaScript that uses a specific export from the WASM module instead of letting `init()` call `main` like we normally see: https://github.com/Zageron/pixels-shadow-dom-example/blob/110ee1da7de4155619fa572d7fb1af9e2e59f83b/web/index.js

I don't actually know anything about why this user decided to do it this way, but I did want to share it as an example of something in the wild that `run-wasm` won't be able to handle in its current state.

**Comment by rukai** [comment]
I think the `main` approach is typically used when we want rust to own the world i.e. we have written a rust app that we also want to run on the web.
This is the kind of use case that cargo-run-wasm is trying to handle.

The calling into specific functions approach is typically used when we want rust to provide some functionality to a javascript stack.
cargo-run-wasm isnt really interested in handling this approach because its expected that you want full control of your stack in that case.
